#lobby-position: [x,x,x,levelname]
#item:
#  - name: xxx
#    id: 1
#    command: /xxx
#hub-when-join: true
#hub-title: xxxx
#hub-subtitle: xxx
#hub-actionbar: xxx
#hub-message: xxx
#lighting-when-hub: true